// Code generated by hertz generator.

package item

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemMw() []app.HandlerFunc {
	// your code...
	return nil
}
