// Code generated by hertz generator.

package item

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yxq98/hz_demo/biz/dal/mysql"
	item "github.com/yxq98/hz_demo/biz/model/item"
)

// GetItem .
// @router /item [GET]
func GetItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req item.GetItemRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	dbItem, err := mysql.NewItemDAO(ctx).GetItemByID(ctx, req.GetID())
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	var resp *item.GetItemResponse
	if dbItem != nil {
		resp = &item.GetItemResponse{
			Item: &item.Item{
				ID:   dbItem.ID,
				Name: dbItem.Name,
			},
		}
	}

	c.JSON(consts.StatusOK, resp)
}
